### ISSUE TITLE
While performing a Direct WFS Conformance test the validator will report a SpatialFilter error for multipoint geometries due to an issue in CITE test

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#208]
While performing a **Download service - Direct WFS** Conformance test for a WFS that serves spatial features that are encodes as **multipoint geometry** the validator will report a **SpatialFilter error (OGC 09-026r2, A.8)** due to the following issue in CITE test: https://github.com/opengeospatial/ets-wfs20/issues/164

Link to test: https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities

Result of the test: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID70a9a270-6b58-42a3-92b9-19d66767935b.html

A separate issue #209 is reported for the Spatial Join CITE issue that can be seen in the above result of the test.

No errors are reported for feature types that are polygon, line or point. Only multipoint, multiline or multipolygons geometries are affected. Multipoint geometries are for example present in the Environmental Monitoring Networks that are part of the Environmental Monitoring Facilities schema/TG.

Until this issue will be fixed in CITE, this test should be skipped either for multipoint, multipolygons and multilines geometries, either should be skipped at all for all geometries (if getting the geometry type is to difficult).

It would be highly appreciated if the EC validator would not be tied to other validators with their own issues.

Best regards,
Iurie Maxim
Essenys Software
Romania

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your suggestions.

The INSPIRE Reference Validator is designed to be modular and to make use of OGC TEAM Engine so we do not reinvent the wheel. The issue should be solved in TEAM Engine.

You might be interesting in opening this issue in the corresponding OGC repository.

Regards

**Comment by iuriemaxim** [comment]
As it was asked to open this issue in the corresponding OGC repository, it should be seen that the issue was already opened in the corresponding OGC repository as it was mentioned in the description of the issue (opengeospatial/ets-wfs20#164). Indded it was a mistake as the issue is actually opengeospatial/ets-wfs20#163.

I agree that the wheel should not be reinvented, but as the OCG CITE Team Engine test for WFS has some issues that affect the INSPIRE Official ETF validator, something should be done at the level of the ETF validator.

Because the INSPIRE Official ETF validator is used:
- by data providers
- by national representatives 
- by EC
until this issue will be fixed in CITE, this test should be skipped in the validator in order not to trigger wrong errors.

**Comment by danielnavarrogeo** [comment]
answered in #215

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, I can see that OGC is working to fix this issue (the work is indicated as being in progress). Let's see how this develops.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
we are in contact with OGC and we have been informed that:
* the [issue](https://github.com/opengeospatial/ets-wfs20/issues/163) was solved and the corresponding [PR](https://github.com/opengeospatial/ets-wfs20/pull/154) merged
* the change will be effective since the next TEAM Engine release, planned by the end of April

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
the OGC CITE TEAM informed us about the new release of the OGC Validation Tools, where the fix to this issue is also included. Please find some more information below.

Can you please check and confirm that this error has been fixed?

Thank you,
Marco

__________________________________________

OGC Beta Validator Website
——————————————
http://cite.opengeospatial.org/te2/

Two test suites were updated:

- WFS 2.0 revision 1.33
- OM 2.0 revision 0.4

In addition, both test suites are available on Docker Hub:

- https://hub.docker.com/r/ogccite/ets-wfs20
- https://hub.docker.com/r/ogccite/ets-om20

**Comment by iuriemaxim** [comment]
I confirm that SpatialFilter error is not provided anymore by CITE test for our service, as it was fixed in CITE.

Link that is passing the SpatialFilter test::

https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetCapabilities

Only Spatial Join was not fixed. See issue https://github.com/inspire-eu-validation/community/issues/209
It should be marked as ”issue”, not as ”discussion”.

The SpatialFilter issue can be closed

Iurie

**Comment by danielnavarrogeo** [comment]
We have added a new label for this cases named 'external dependency'.

We will close the issue now.
