### ISSUE TITLE
While performing a Direct WFS Conformance test the validator will report NullPointerException errors due to an issue in CITE test

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#210]
While performing a Download service - Direct WFS Conformance test for a WFS, the validator will report NullPointerException due to the following issue in CITE test: https://github.com/opengeospatial/ets-gml32/issues/46

Link to test:
https://geoportal.meteoromania.ro/GIS/wfs?service=WFS&request=GetCapabilities

Validation result:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID3c2e591c-ae6c-47c4-9e39-fc76e5f61d63.html

All errors that are reported as: ”OGC TEAM Engine reported a failed test: No message provided. Exception class java.lang.NullPointerException” are due to the CITE issue https://github.com/opengeospatial/ets-gml32/issues/46.

Other errors are due to other reasons as this is not an INSPIRE Compliant WFS.

Seems that nothing can be done in the EC validator to avoid triggering these errors, so the CITE test should be fixed.

This was reported for others to know if would see **OGC TEAM Engine reported a failed test: No message provided. Exception class java.lang.NullPointerException** errors while performing a Direct WFS Conformance test. If anything can be done in the Validator in order not to report these issues, but still to perform those tests, it would be fine.

It would be highly appreciated if the EC validator would not be tied to other validators with their own issues.

Best regards,
Iurie Maxim
Essenys Software
Romania

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your suggestions.

The INSPIRE Reference Validator is designed to be modular and to make use of OGC TEAM Engine so we do not reinvent the wheel. The issue should be solved in TEAM Engine.

You might be interesting in opening this issue in the corresponding OGC repository.

Regards

**Comment by iuriemaxim** [comment]
As it was asked to open this issue in the corresponding OGC repository, it should be seen that the issue was already opened in the corresponding OGC repository as it was mentioned in the description of the issue (opengeospatial/ets-gml32#46).

I agree that the wheel should not be reinvented, but as the OCG CITE Team Engine test for WFS has some issues that affect the INSPIRE Official ETF validator, something should be done at the level of the ETF validator.

Because the INSPIRE Official ETF validator is used:
- by data providers
- by national representatives 
- by EC
until this issue will be fixed in CITE, this test should be skipped in the validator in order not to trigger wrong errors.

**Comment by danielnavarrogeo** [comment]
answered in #215

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, looking at the thread in the OGC issue tracker, I see that the issue has been correctly recognized as a bug. Let's wait for further developments on their side.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
we are in contact with OGC and we have been informed that:
* the [issue](https://github.com/opengeospatial/ets-gml32/issues/46) was solved and the corresponding [PR](https://github.com/opengeospatial/ets-gml32/pull/47) merged
* the change will be effective since the next TEAM Engine release, planned by the end of April

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
the OGC CITE TEAM informed us about the new release of the OGC Validation Tools, where the fix to this issue is also included. Please find some more information below.

Can you please check and confirm that this error has been fixed?

Thank you,
Marco

__________________________________________

OGC Beta Validator Website
——————————————
http://cite.opengeospatial.org/te2/

Two test suites were updated:

- WFS 2.0 revision 1.33
- OM 2.0 revision 0.4

In addition, both test suites are available on Docker Hub:

- https://hub.docker.com/r/ogccite/ets-wfs20
- https://hub.docker.com/r/ogccite/ets-om20

**Comment by iuriemaxim** [comment]
@carlospzurita please assign my coleague @danieluct if possible

See also comments from last month on https://github.com/opengeospatial/ets-gml32/issues/46

Iurie

**Comment by danieluct** [comment]
The original fix was reverted before the release as it was breaking existing functionality. The new fix will only be included in the next release for ets-gml32 (https://github.com/opengeospatial/ets-gml32/milestone/8?closed=1). Unfortunately, no due date exists at the moment for this.

**Comment by iuriemaxim** [comment]
@carlospzurita the label “ready for testing” should be removed until the fix will be implemented in CITE.
Issue still exist.
However there are solutions to avoid this error if using a custom compiled WFS server. Thats why WFS service from https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetCapabilities would not triger this error.

**Comment by iuriemaxim** [comment]
Service to test that the NullPointerException issue was not fixed:
https://gis.essensys.ro/WIGOS/WFS/Capabilities

Test result:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID5dda026c-b98d-4e75-83a4-8515178b60e3.html

![17323044-360A-4313-AB39-A126D346812D](https://user-images.githubusercontent.com/20813598/85865439-8f16bf00-b7ce-11ea-88d9-5e1a5a7a1c62.jpeg)

**Comment by iuriemaxim** [comment]
@carlospzurita Please remove the label “ready for testing” until the fix will be implemented in CITE.
Issue still exist. The test fails.

**Comment by iuriemaxim** [comment]
@carlospzurita The tag "ready for testing" should be removed as already mentioned, due to the fact that the issue was not solved.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim and @danieluct, 
did you have a chance to check whether this fix was finally included in (at least) the beta instance of the OGC TEAM Engine? The staging instance of the INSPIRE Reference Validator is linked to the beta instance of the TEAM Engine, so you can test it directly there.

**Comment by iuriemaxim** [comment]
@MarcoMinghini

OGC fixed this issue.

I tested on the Inspire staging instance the service that is indicated above ( https://gis.essensys.ro/WIGOS/WFS/Capabilities) and NullPointerException messages are not appearing anymore.

This issue can be closed.
