### ISSUE TITLE
While performing a Direct WFS Conformance test the validator will report a TemporalFilter error for voidable temporal elements that are not provided, due to an issue in CITE test

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#219]
Details are provided in the discussion #216.
The error in the due to this issue in the OGC CITE TeamEngine https://github.com/opengeospatial/ets-wfs20/issues/157.

Shortly, the ETF validator provides this error for Spatial Filter
![image](https://user-images.githubusercontent.com/20813598/74669760-7b1fd880-51b0-11ea-8581-a5a5c3f1316a.png)

while performing a filter on a voidable element, that is not provided within the features served by the WFS.

Link to test the WFS service:
https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetCapabilities

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
we are in contact with OGC and we have been informed that:
* the [issue](https://github.com/opengeospatial/ets-wfs20/issues/157) was solved and the corresponding [PR](https://github.com/opengeospatial/ets-wfs20/pull/158) merged
* the change will be effective since the next TEAM Engine release, planned by the end of April

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
the OGC CITE TEAM informed us about the new release of the OGC Validation Tools, where the fix to this issue is also included. Please find some more information below.

Can you please check and confirm that this error has been fixed?

Thank you,
Marco

__________________________________________

OGC Beta Validator Website
——————————————
http://cite.opengeospatial.org/te2/

Two test suites were updated:

- WFS 2.0 revision 1.33
- OM 2.0 revision 0.4

In addition, both test suites are available on Docker Hub:

- https://hub.docker.com/r/ogccite/ets-wfs20
- https://hub.docker.com/r/ogccite/ets-om20

**Comment by iuriemaxim** [comment]
I confirm that SpatialFilter error is not provided anymore by CITE test for our service, as it was fixed in CITE.

Link that is passing the TemporalFilter test::

https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetCapabilities

Only Spatial Join was not fixed. See issue #209
It should be marked as ”issue”, not as ”discussion”.

The TemporalFilter issue can be closed

Iurie

**Comment by danielnavarrogeo** [comment]
We have added a new label for these cases named 'external dependency'.

We will close the issue now.

**Comment by Kate-Lyndegaard** [comment]
Hi,
I have a question about several temporal filter errors which I had hoped would be resolved in the INSPIRE validator with the latest fixes in the OGC CITE [WFS 2.0 revision 1.33](https://cite.opengeospatial.org/te2/), fix [#157](https://github.com/opengeospatial/ets-wfs20/issues/157).

Direct WFS Conformance class: Temporal filters
org.opengis.cite.iso19142.basic.filter.temporal.AfterTests: Tests `validTo` property which does not exist in data
org.opengis.cite.iso19142.basic.filter.temporal.BeforeTests: Tests `validTo` property which does not exist in data
org.opengis.cite.iso19142.basic.filter.temporal.DuringTests: Tests `validTo` property which does not exist in data

`validTo` is a nillable property with 0 cardinality which does not occur in my dataset. Any idea why this error is occurring in the staging instance of the validator? 

Test WFS: https://test.haleconnect.de/ows/services/org.315.2d4db8c9-1736-406c-9b54-fc0ca527e2a3_wfs/org.315.ed014538-597a-4254-8844-60ee149fcfe0?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Any insight would be greatly appreciated.

Kind regards,
Kate

**Comment by iuriemaxim** [comment]
@Kate-Lyndegaard If necessary please open another ticket. All our WFS services are passing the OGC temporal filter test. Last test was done last week in production.

As far as I remember we do not have any validTo elements neither.

One of the services to test:
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetCapabilities

Only the spatial join CITE test is still not fixed.

Iurie

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

Would you kindly create a new issue for this problem? It seems to be a separated matter from the original one posted here.

Kind regards
