### ISSUE TITLE
Code lists cannot be accessed

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#268]
- I executed a test using the 4 GML 'basic' conformance classes
- error message: "System error in the Executable Test Suite. Please contact a system administrator. Error information: Code list [...] cannot be accessed."
- Screenshot: 
![grafik](https://user-images.githubusercontent.com/34163838/78122862-9f0c4600-740d-11ea-8679-bd5b0ad1c67d.png)
- The same message occurs for the following tests:
Test ID | EID12abc9dc-27ff-406f-8cdd-f55db5523c97
Test ID | EID74abd92b-9225-4d73-a03f-db7bd3471bd6
Test ID | EIDa81c147e-72b2-4054-9d3d-26b1091b641f
Test ID | EID5f5466b9-1f77-4577-aef8-2fdee94f7ad2
- the data belongs to one of my customers. If it is needed for reproducing the issue, I will need to clarify with them if I cann pass it on.

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

We are analyzing this issue and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

We have identified an issue with the reverse proxy which is already solved.

Would you mind testing it again and provide us feedback?

Regards

**Comment by JohannaOtt** [comment]
I just checked and it looks good to me. Thank you for the quick solution!

**Comment by danielnavarrogeo** [comment]
Thank you @JohannaOtt

**Comment by JohannaOtt** [comment]
@danielnavarrogeo This issue is back: 
![grafik](https://user-images.githubusercontent.com/34163838/79310147-bd893b80-7efb-11ea-94af-80bd2af37f3e.png)

**Comment by carlospzurita** [comment]
@JohannaOtt please can you try again? We restarted the proxy

**Comment by JohannaOtt** [comment]
LGTM
