### ISSUE TITLE
Romanian Conformity title (Regulation 1089/2010) it's not validate

### ISSUE THREAD

**Issue by SimonaBunea** [INSPIRE-MIF/helpdesk-validator#402]
I'm trying to validate the metadata from URL: https://inspire.insp.gov.ro/geoportal/rest/metadata/item/6746c7add0e746f89d45d9e31961e75a/xml
The conformity title on Romanian language it's copied from https://op.europa.eu/en/publication-detail/-/publication/6c9b0d4b-831f-47fe-b551-ac13604d9797/language-ro.
I verified also on http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_rum.xsd, an the title it's ok, with correct special characters - correct unicode.
So, the validator give the errors on this title: The metadata record set has 1 record(s) with errors for this assertion.
XML document 'csw.xml', record '1583995569364r670694296583935': No citation of the Implementing Rules for Interoperability of spatial datasets and services (Regulation 1089/2010) has been found, or the text does not match the expected one.
I verify on https://github.com/inspire-eu-validation/ets-repository/blob/424ec70639a0c8d58f5a5dfa49e212dcfb721fde/schemas/common/1.0/enums/enum_rum.xsd and there the wrong special character are used. 
Please, we can verify and corrected.
I attached the difference between the special character used in the inspire validator- xsd and the publication title of Regulation 1089/2010.

Best regards,
Simona Bunea
Romania

[InspireValidatorRumXSD_vs_TitleConformityRegulation_SpecialCharacter_RUM.pdf](https://github.com/inspire-eu-validation/community/files/5311246/InspireValidatorRumXSD_vs_TitleConformityRegulation_SpecialCharacter_RUM.pdf)

**Comment by SimonaBunea** [comment]
Sorry, but in http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_rum.xsd it is also wrong.

**Comment by carlospzurita** [comment]
Thank you for raise awareness of this issue on the Unicode characters. We are going to check how to proceed with the modifications and get back to you whenever this is solved.

**Comment by iuriemaxim** [comment]
That's correct: Ș, ș, Ț, ț are the correct Romanian characters.

Romanian characters are found in ISO/IEC 8859-16 (Latin 10) from 2001 (https://en.wikipedia.org/wiki/ISO/IEC_8859-16)

The similar looking characters from the proprietary Windows 1250 Code page are not Romanian, but Turkish characters
 https://en.wikipedia.org/wiki/Windows-1250 as they are using cedilla, while the Romanian characters are using a comma below the characters. More details about the confusion are found here https://en.wikipedia.org/wiki/Cedilla,

**Comment by MarcoMinghini** [comment]
Dear @SimonaBunea,
thanks for raising this issue, which - as you correctly spotted out - is an issue in the Validator caused by an issue in the XSD schema http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_rum.xsd. This means that the schema should be fixed first, then the Validator will follow.

We are currently in the process of defining a new governance mechanism for many INSPIRE artefacts, including also the schemas, which will clarify how change requests for those artefacts can be done, where, when, and what will be the process leading to their acceptance. We will come back to this issue as soon as the new mechanism is in place.

**Comment by SimonaBunea** [comment]
Dear @MarcoMinghini ,

Do you think that this problem will be solved until the monitoring process 2020, 15-12-2020?
At the same time I picked up a ticket on HelpDesk Geoportal regarding the same citation - https://ies-svn.jrc.ec.europa.eu/issues/3890
No answer so far.
We are now in the process of transforming the metadata documents from scheme TG1.3 to TG2.0.
If these problems are not resolved, it means that the following monitoring indicators will be 0:
- the compliance of the metadata for the data sets (MDi1.1) 
- the conformity of the data sets (DSi2).
And that's not because of us. Correct me if I'm wrong.

Best regards,
Simona Bunea

**Comment by MarcoMinghini** [comment]
Dear @SimonaBunea,
the problem has been fixed. We changed the schema http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_rum.xsd and the test on the metadata you used now passes. Please confirm that the problem is solved and we will close this issue.

Please note that we exceptionally proceeded to change the schema in such a short time for two reasons: i) the mistake was obvious and the change did not need particular discussion and endorsement; and ii) the issue had an impact on the Monitoring and Reporting indicators.

As mentioned in my first comment above, this was not an issue of the Validator. However, in general please remember that there is a public [release plan](https://github.com/inspire-eu-validation/community/tree/master/release%20strategy) for the Validator that we published at the beginning of 2020. According to this document, the last release of the Validator before the annual Monitoring and Reporting deadline is (was) in September. This was decided in order to release the software used for Monitoring and Reporting 3 months in advance, and to allow the community to start testing much earlier and report all bugs before the last release in September.

**Comment by SimonaBunea** [comment]
Dear @MarcoMinghini ,

Thank you for quick solving of this issue.
I checked with the metadata URL: https://inspire.insp.gov.ro/geoportal/rest/metadata/item/6746c7add0e746f89d45d9e31961e75a/xml and everything is ok now.
So, you can close this tichet.
Thank you once again for your support!

Have a nice day!
Simona Bunea
