### ISSUE TITLE
OGC Tests not working on staging

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#408]
While trying to retest a WFS service, It seems that the OGC tests are not working on staging environment.

![image](https://user-images.githubusercontent.com/20813598/95292542-5204a300-087a-11eb-8556-e4275765208d.png)

On production environment it works. Testing on staging was necessary in order to see the effects of changes performed by OGC in their tests.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

We tried to replicate this issue and we got the full report from OGC, although it took a little bit longer than usual for the retrieval of results and generating the TestReport.

@ghobona can you confirm that everything is ok on your side (beta instance of TEAM Engine)?

**Comment by carlospzurita** [comment]
@iuriemaxim is this your TestRun? http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDf2f3cf6f-ddbd-4aa3-b8d9-284347f48fc1.html

As stated in the last comment, the TestRun does ends and generates a TestReport, but it seems that the results take too long to be retrieved and the TestRun monitor gets disconnected.

**Comment by iuriemaxim** [comment]
Yes this is the test. On production the same test is displayed, while on staging not.  On staging the test takes only 2 minutes (at least this is what is displayed on the test), so I  do not think that the reason is that the test take too long to be retrieved.

**Comment by iuriemaxim** [comment]
Sometimes I received even this (on staging) so maybe it is not due to an external dependency,

![image](https://user-images.githubusercontent.com/20813598/95363791-9888ea80-08d8-11eb-941c-e8fa5d5c28fb.png)

**Comment by ghobona** [comment]
Both the Beta and Production TEAM Engine instances are working normally.

The test took 2 minutes to run on both of them.

The duration is proportional to the number of conformance classes tested. Since the WFS implementation being tested supports many of the conformance classes, the test takes long to complete. It does however complete. Below is an extract from the report generated.

![Screenshot 2020-10-07 at 18 10 29](https://user-images.githubusercontent.com/18121038/95365094-8d7a8e00-08c9-11eb-8923-1c9c662c714c.png)

The conformance class that fails the Spatial Joins one. The reason for the failure result is shown on the screenshot below.

![Screenshot 2020-10-07 at 18 12 26](https://user-images.githubusercontent.com/18121038/95365122-9a977d00-08c9-11eb-943c-eb099b4ee234.png)

Cc: @dstenger

**Comment by iuriemaxim** [comment]
@carlospzurita Probably it is similar with https://github.com/inspire-eu-validation/community/issues/395, which is not related to OGC tests

**Comment by iuriemaxim** [comment]
@ghobona @dstenger Based on this fix https://github.com/opengeospatial/ets-wfs20/issues/175 the test should pass isn't it?
@carlospzurita this is a new error that was not encountered in the past during so many tests performed on the same service that was not changed.

**Comment by iuriemaxim** [comment]
@carlospzurita As this is not yet closed, should I try to test again to see if the error can be replicated, especially as the Spatial Join was fixed in the TeamEngine Staging environment ?

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

Please, if you can, repeat the test to check if this error is persisting. It is unlikely that this error is related to #395, as that error seems to come from different engines of feature validation.

**Comment by iuriemaxim** [comment]
@carlospzurita I tried to replicate the issue but I was surprised to see that the WFS Direct Access Test dissapeared from the validator
Now it looks like this:

![image](https://user-images.githubusercontent.com/20813598/102284306-a001eb00-3f3c-11eb-81d6-2611b279d049.png)

All these tests vanished:

![image](https://user-images.githubusercontent.com/20813598/102284510-f2dba280-3f3c-11eb-9573-84ea4a265edd.png)

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

The tests are in fact gone from the staging instance, and we are looking into it because it may have disappeared in our testing process. The test for Direct WFS is still present on the [production instance](https://inspire.ec.europa.eu/validator/), and yo may replicate there this issue

**Comment by iuriemaxim** [comment]
Testing it several times.

Now it performs well. Always the texts encircled in red now appear and the results are accessible.

![image](https://user-images.githubusercontent.com/20813598/102463185-72f42c00-4053-11eb-9739-3a46a39a1a9f.png)

This issue was present only on staging. Now it cant be replicated anymore on staging so it was fixed. Most probably was related with the communication between the validator and the TeamEngine, both on their stagining environment.

The issue can be therefore closed.
