### ISSUE TITLE
Upload of ISO19115-2 XML documents for validation

### ISSUE THREAD

**Issue by enricoboldrini** [INSPIRE-MIF/helpdesk-validator#65]
The validator raises an error during the upload file phase (just at the beginning), preventing the actual validation tests to be executed (in this case metadata for interoperability test).
I'm attaching the file raising the issue.
[inspire.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/3284688/inspire.zip)
The error provided is:
"Upload failed: The test object type could not be determined. Check the uploaded / referenced resource. Uploaded files may only contain test data and no other files. If the problem persists, please contact the ETF system administrator of the server."

The cause could be that this profile is based on the second part of ISO 19115 (ISO19115-2, gmi package). Example given, the root element is gmi:MI_Metadata instead of gmd:MD_Metadata.
Kind regards,
Enrico

**Comment by josemasensio** [comment]
Dear @enricoboldrini,

We have reviewed the ETF logs and you are right. The file can't be uploaded because the root element is gmi:MI_Metadata instead of gmd:MD_Metadata. 

The checks that the ETF runs to see if it is a metadata file are:

    "(local-name() = 'GetRecordsResponse' and starts-with(namespace-uri(), 'http://www.opengis.net/cat/csw/')) or "
    "(local-name() = 'GetRecordByIdResponse' and starts-with(namespace-uri(), 'http://www.opengis.net/cat/csw/')) or "
    "(local-name() = 'MD_Metadata' and namespace-uri() = 'http://www.isotc211.org/2005/gmd')"

The possible solution would be to add one more line providing for the verification of that label:

    "(local-name() = 'MI_Metadata' and namespace-uri() = 'http://www.isotc211.org/2005/gmi')"

Although we don't know if that will be in line with the Technical Guidelines.

@MarcoMinghini we add the "discussion" label to this issue.

**Comment by MarcoMinghini** [comment]
MD TG 1.3 (the one used in this case for validation) states on page 62 that:

> An INSPIRE Metadata Set is an instance of:
> • the class MD_Metadata (from ISO 19115),
> • the class MI_Metadata (from ISO 19115-2),
> • or, an instance of any community specialisation of one of these two classes.

while MD TG 2.0, with reference to ISO 19115-2, states on page 25 that

> It was decided in the MIWP-8 sub-group that new versions of the ISO 19115 standard were out of scope for this version of this specification. The future versions of this Technical Guidelines may be revised taking into account the new ISO 19115 family standards.

Therefore, when validating MD TG 1.3, the solution proposed by @bilbomaticaue looks ok.

**Comment by MartinePaepen** [comment]
What is the status?
We need to evolve to INSPIRE 19115-2 and can't validate any more using the online validator.
This is a pity as the standard is required now.
Couldn't this have priority as it seems a small fix.

Thanks,
Martine

**Comment by tcassaert** [comment]
> Dear @enricoboldrini,
> 
> We have reviewed the ETF logs and you are right. The file can't be uploaded because the root element is gmi:MI_Metadata instead of gmd:MD_Metadata.
> 
> The checks that the ETF runs to see if it is a metadata file are:
> 
> ```
> "(local-name() = 'GetRecordsResponse' and starts-with(namespace-uri(), 'http://www.opengis.net/cat/csw/')) or "
> "(local-name() = 'GetRecordByIdResponse' and starts-with(namespace-uri(), 'http://www.opengis.net/cat/csw/')) or "
> "(local-name() = 'MD_Metadata' and namespace-uri() = 'http://www.isotc211.org/2005/gmd')"
> ```
> 
> The possible solution would be to add one more line providing for the verification of that label:
> 
> ```
> "(local-name() = 'MI_Metadata' and namespace-uri() = 'http://www.isotc211.org/2005/gmi')"
> ```
> 
> Although we don't know if that will be in line with the Technical Guidelines.
> 
> @MarcoMinghini we add the "discussion" label to this issue.

@josemasensio  Could you please elaborate on where this change should be made?

**Comment by MartinePaepen** [comment]
@MarcoMinghini and @josemasensio we managed to upload the MI_Metadata file (ISO 19115-2:2019) but the tool doesn't validate this file. And no errors are generated.
Any idea what is wrong?
Thanks,
Martine

**Comment by felnne** [comment]
Hi,

I also have this problem trying to validate this [candidate record](https://gist.githubusercontent.com/felnne/db57a62d1a1360484a404c375a1f6f1d/raw/f99d9f29185de6744209021bca48e5e25ee172a7/candidate-record.xml)

At the moment I'm unsure whether I've implemented this correctly or not so it would be really useful if this was supported.

**Comment by dperezBM** [comment]
Dear @enricoboldrini, @MartinePaepen, @felnne,
With the intention to resume this problem, could you please confirm that the error is still occurring? And if so, could you please send us the files that are failing?

Thank you very much in advance.

Best regards

**Comment by enricoboldrini** [comment]
Dear @dperezBM ,

I confirm the error still occurs. You can try with the "Metadata for interoperability" test and the following file: https://www.seadatanet.org/content/download/4535/file/CSR_ISO19139_full_example_v5.2.0.xml

Kind regards,
Enrico

**Comment by MartinePaepen** [comment]
Dear,

Yes the problem is still occurring.
I have now a bigger problem as the schema's provided as standards redirect to schema's  which are no longer online available. Which is a very big issue for us.


I get always the same errors because of unexisting  http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.......xsd"/<http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.......xsd%22/>>

Taking https://www.isotc211.org/2005/gmi/gmi.xsd
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<xs:schema xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.isotc211.org/2005/gmi" elementFormDefault="qualified" version="0.1">

<xs:annotation>
<xs:documentation>This file was generated from ISO TC/211 UML class diagrams == 07-30-2010 11:34:37 ====== </xs:documentation>
</xs:annotation>

<xs:include schemaLocation="../gmi/metadataEntitySet.xsd"/>
<xs:include schemaLocation="../gmi/acquisitionInformation.xsd"/>
<xs:include schemaLocation="../gmi/dataQualityInformation.xsd"/>
<xs:include schemaLocation="../gmi/spatialRepresentationInformation.xsd"/>
<xs:include schemaLocation="../gmi/contentInformation.xsd"/>



</xs:schema>

https://www.isotc211.org/2005/gmi/acquisitionInformation.xsd
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gmd="http://www.isotc211.org/2005/gmd" targetNamespace="http://www.isotc211.org/2005/gmi" elementFormDefault="qualified" version="0.1">

<xs:annotation>
<xs:documentation>This file was generated from ISO TC/211 UML class diagrams == 07-30-2010 11:34:36 ====== </xs:documentation>
<xs:documentation>2012-12-08: Documentation of MI_Objective_Type. Typo reported by XMG: "temportal" replaced by "temporal".</xs:documentation>
</xs:annotation>

<xs:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gco" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gss" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gss/gss.xsd"/>



<xs:complexType name="MI_Requirement_Type">
<xs:annotation>
<xs:documentation>Description: requirement to be satisfied by the planned data acquisition - shortName: Requirement</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="gco:AbstractObject_Type">
<xs:sequence>
<xs:element name="citation" type="gmd:CI_Citation_PropertyType" minOccurs="0"/>
<xs:element name="identifier" type="gmd:MD_Identifier_PropertyType"/>
<xs:element name="requestor" type="gmd:CI_ResponsibleParty_PropertyType" maxOccurs="unbounded"/>
<xs:element name="recipient" type="gmd:CI_ResponsibleParty_PropertyType" maxOccurs="unbounded"/>
<xs:element name="priority" type="gmi:MI_PriorityCode_PropertyType"/>
<xs:element name="requestedDate" type="gmi:MI_RequestedDate_PropertyType"/>
<xs:element name="expiryDate" type="gco:DateTime_PropertyType"/>
<xs:element name="satisifiedPlan" type="gmi:MI_Plan_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:element name="MI_Requirement" type="gmi:MI_Requirement_Type"/>

<xs:complexType name="MI_Requirement_PropertyType">
<xs:sequence>
<xs:element ref="gmi:MI_Requirement" minOccurs="0"/>
</xs:sequence>
<xs:attributeGroup ref="gco:ObjectReference"/>
<xs:attribute ref="gco:nilReason"/>
</xs:complexType>

<xs:complexType name="MI_Objective_Type">
<xs:annotation>
<xs:documentation>Description: Describes the characteristics, spatial and temporal extent of the intended object to be observed - shortName: TargetId</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="gco:AbstractObject_Type">
<xs:sequence>
<xs:element name="identifier" type="gmd:MD_Identifier_PropertyType" maxOccurs="unbounded"/>
<xs:element name="priority" type="gco:CharacterString_PropertyType" minOccurs="0"/>
<xs:element name="type" type="gmi:MI_ObjectiveTypeCode_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="function" type="gco:CharacterString_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="extent" type="gmd:EX_Extent_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="pass" type="gmi:MI_PlatformPass_PropertyType" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="sensingInstrument" type="gmi:MI_Instrume


From: Paepen Martine
Sent: Thursday, 6 May 2021 12:03
To: ISO-TC211/XML ***@***.******@***.***>>; ISO-TC211/XML ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [ISO-TC211/XML] Issue with validating ISO 19115-2 MI_Metadata due to removed schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" (#217)

Dear Evert,

As you can see in the
https://standards.iso.org/iso/19115/-2/gmi/1.0/gmi.xsd
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<xs:schema xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://standards.iso.org/iso/19115/-2/gmi/1.0" version="0.1">

<xs:annotation>
<xs:documentation>This file was created by Ted Habermann during May 2015 to correct omissions (gmx, MI_EnvironmentalRecord) in existing gmi schema ====== </xs:documentation>
</xs:annotation>

<xs:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gco" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gss" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gss/gss.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gmx" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd"/>
<xs:include schemaLocation="metadataEntitySet.xsd"/>
<xs:include schemaLocation="contentInformation.xsd"/>
<xs:include schemaLocation="dataQualityInformation.xsd"/>
<xs:include schemaLocation="spatialRepresentationInformation.xsd"/>
</xs:schema>

They refer to http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd
Which don't exist.

Kind regards,
Martine


From: Paepen Martine
Sent: Thursday, 6 May 2021 10:42
To: 'ISO-TC211/XML' ***@***.******@***.***>>; ISO-TC211/XML ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [ISO-TC211/XML] Issue with validating ISO 19115-2 MI_Metadata due to removed schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd" (#217)

Dearn Evert,

Thanks for the feedback.
However I have replaced the schema:
gmi:MI_Metadata xsi:schemaLocation="http://www.isotc211.org/2005/gmi http://www.isotc211.org/2005/gmi/gmi.xsd<http://www.isotc211.org/2005/gmi%20http:/www.isotc211.org/2005/gmi/gmi.xsd>" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
       <gmd:language>


<gmi:MI_Metadata xsi:schemaLocation="http://standards.iso.org/iso/19115/-2/gmi/1.0 http://standards.iso.org/iso/19115/-2/gmi/1.0/gmi.xsd<http://standards.iso.org/iso/19115/-2/gmi/1.0%20http:/standards.iso.org/iso/19115/-2/gmi/1.0/gmi.xsd>" xmlns:gmi="http://standards.iso.org/iso/19115/-2/gmi/1.0" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

And the validation error is still:
[Altova XMLSpy - [INSPIRE (4).txt *]]

So there seems to be a redirect to the schema's which doesn't exist anymore.
Could you please check?

Many thanks,
Martine

**Comment by fabiovinci** [comment]
Dear all,

as mentioned [in this comment](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/253#issuecomment-597751181) for a similar issue, the MD TG states that _new versions of the ISO 19115 standard were out of scope for this version of this specification_.
For addressing this issue a change in the MD TG would be required, which could be done through a [change proposal in the dedicated repository](https://github.com/INSPIRE-MIF/technical-guidelines/issues/new/choose).
