### ISSUE TITLE
Temporal Filter errors in Direct WFS test

### ISSUE THREAD

**Issue by mlcharv** [INSPIRE-MIF/helpdesk-validator#831]
When validating [this WFS](https://contenido.ign.es/wfs-inspire/unidades-administrativas?service=WFS&request=GetCapabilities) on production or staging using the Direct WFS test, the temporal tests fail with the following or similar message: "java.lang.AssertionError: t1 (Instant: 2009-07-06T00:00:00.000+0000) is not related to t2 (Instant: 2013-06-07T23:40:00.000+0000): AFTER. The actual temporal relation is BEFORE." The service configuration seems to be correct and we don't know what the problem could be. We considered the posibility of something wrong with the data type in the database. We made sure the beginLifespanVersion field is of type DateTime so that it can be properly filtered but the errors stayed the same.

![Captura de pantalla de 2022-08-23 11-51-06](https://user-images.githubusercontent.com/111862903/186133355-6db36958-21e8-44c7-8f44-687a71ca9847.png)

This is the test report from the validator:
[Test run on 11 35 - 23.08.2022 with test suite Conformance Class Direct WFS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9401648/Test.run.on.11.35.-.23.08.2022.with.test.suite.Conformance.Class.Direct.WFS.zip)

Thank you!

**Comment by fabiovinci** [comment]
Dear @mlcharv,

the error you reported originates from the OGC WFS 2.0 Conformance Test Suite, looking at the [related OGC repository](https://github.com/opengeospatial/ets-wfs20) it seems that similar issues have been already reported and a solution should be under development.
Please follow the related issues or open a new one:

- https://github.com/opengeospatial/ets-wfs20/issues/185
- https://github.com/opengeospatial/ets-wfs20/issues/226

**Comment by fabiovinci** [comment]
Dear @mlcharv,

the related OGC issues were solved and included in the 1.39 revision of the OGC WFS Conformance Test Suite, so these fixes are also available in the Validator.

Trying to validate your WFS it seems there is a timeout error ([see report](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID1a7b6df2-2e71-40e3-a142-bd343139b78f)) and the OGC WFS Test Suite cannot be executed.

Validating the WFS with the [OGC Validator](https://cite.opengeospatial.org/teamengine/), the mentioned errors are no longer present.

See the validation log and report below:

> Testing suite tns:ets-wfs20-1.40 in Test Mode with defaultResult of Pass ...
> 
> ******************************************************************************************************************************
> 
>    Testing tns:Main type Mandatory in Test Mode with defaultResult Pass (s0145)...
> 
>       Assertion: The test subject satisfies all applicable constraints.
> 
>       Test suite: wfs20-1.40
> 
>       ======== Test groups ========
> 
>       Preconditions
> 
>           Passed: 3 | Failed: 0 | Skipped: 0
> 
>       All GML application schemas
> 
>           Passed: 7 | Failed: 0 | Skipped: 0
> 
>       GML application schemas defining features
> 
>           Passed: 2 | Failed: 0 | Skipped: 0
> 
>       Simple WFS
> 
>           Passed: 31 | Failed: 0 | Skipped: 0
> 
>       Basic WFS
> 
>           Passed: 93 | Failed: 1 | Skipped: 15
> 
>       Temporal filter
> 
>           Passed: 0 | Failed: 0 | Skipped: 30
> 
>       Spatial filter
> 
>           Passed: 24 | Failed: 2 | Skipped: 0
> 
>       Spatial joins
> 
>           Passed: 0 | Failed: 0 | Skipped: 1
> 
>       Transactional WFS
> 
>           Passed: 0 | Failed: 0 | Skipped: 23
> 
>       Locking WFS
> 
>           Passed: 0 | Failed: 0 | Skipped: 13
> 
>       Response paging
> 
>           Passed: 0 | Failed: 0 | Skipped: 2
> 
>       Manage stored queries
> 
>           Passed: 0 | Failed: 0 | Skipped: 6
> 
>       Feature versions
> 
>           Passed: 0 | Failed: 0 | Skipped: 4
> 
>       
> 
>       
> 
>       See detailed test report in the TE_BASE/users/fabio.v/s0145/html/ directory.
> 
>       Test method getFeatureInOtherCRS: 
> 
>                     Unexpected @srsName value on element srsName expected [http://www.opengis.net/def/crs/EPSG/0/4326] but found [urn:ogc:def:crs:EPSG:6.3:4326]
> 
>       Test method invalidGeometryOperand: 
> 
>                     Unexpected HTTP status code.
> 
>       Test method invalidGeometryOperand: 
> 
>                     Unexpected HTTP status code.
> 
>    Test tns:Main Failed
> 
> Suite tns:ets-wfs20-1.40 Failed



[Test Session Results.pdf](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15376258/Test.Session.Results.pdf)

Could you please check and confirm that the errors are no longer present?

**Comment by CeciliaPH** [comment]
Dear @fabiovinci and dear @mlcharv 

We checked our service https://www.ign.es/wfs-inspire/unidades-administrativas?request=GetCapabilities&service=WFS
against the INSPIRE validator and, while the temporary filter issues are solved, the spatial filter error is still there.

org.opengis.cite.iso19142.basic.filter.spatial.BBOXTests
invalidGeometryoperand
OGC TEAM Engine reported a failed test: Unexpected HTTP status code.

We opened the saved POST request data, and saved response and we can not find any hint about anomalous data or operand.

I have made a little research and discussion about this seems to be happening here:
https://github.com/opengeospatial/ets-wfs20/issues/247

If there is something we can do to workaround this issue or if you know when this issue will be incorporated to the inspire validator, please let us know.

Thanks in advance,

Cecilia

**Comment by fabiovinci** [comment]
Dear @CeciliaPH,

I looked at your service and its validation report and you are right about the "Unexpected HTTP status code" error message being unclear.
Looking at the linked OGC issue and at the related issues, it seems the reported issues are different, I suggest opening a dedicated issue for your specific error.

The INSPIRE Validator uses the production version of the [OGC Validator](https://cite.opengeospatial.org/teamengine/) and thus the related Test Suite versions. E.g.: for WFS 2.0 the current test suite version is 1.40.

So, any fix implemented by OGC is available in the INSPIRE Validator if the related Test Suite is published in the OGC Validator.

Example:
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/bcabf435-0db2-42c7-ad6a-59090f80b31a)

**Comment by CeciliaPH** [comment]
Thanks for your help. I created a new issue. Let's see if we can solve it.

https://github.com/opengeospatial/ets-wfs20/issues/275

**Comment by fabiovinci** [comment]
Dear @CeciliaPH,
It seems your issue has been resolved, but the solution is still only available in the [Beta environment](https://cite.ogc.org/te2/) (not yet in the [Production environment](https://cite.ogc.org/teamengine/)).
So, it is not yet available in the production instance of the validator!
